INSERT INTO COZINHA (NOME) VALUES ('Tailandesa')
INSERT INTO COZINHA (NOME) VALUES ('Indiana')
INSERT INTO COZINHA (NOME) VALUES ('Japonesa')

INSERT INTO RESTAURANTE (NOME, TAXA_FRETE) VALUES ('McDonalds', 9.90)
INSERT INTO RESTAURANTE (NOME, TAXA_FRETE) VALUES ('BurgerKing', 5.50)
